[package]
name = "collections"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { workspace = true, features = ["serde", "v7"] }
axum = { workspace = true }
serde_json = { workspace = true }
nanoid = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
svix-ksuid = { workspace = true, features = ["serde"] }
sqlx = { workspace = true, features = [
    "runtime-tokio",
    "tls-rustls-aws-lc-rs",
] }
[lints]
workspace = true
